"""Constants for dycap collector."""

from __future__ import annotations

# WebSocket keepalive settings
WS_DOUYU_HEARTBEAT_SECONDS = 40
WS_READ_IDLE_TIMEOUT_SECONDS = 180
WS_SERVER_REFRESH_INTERVAL_SECONDS = 25
WS_RECOVERY_BACKOFF_SECONDS = 5

# Retry settings
RETRY_ATTEMPTS_WS_CONNECT = 3
RETRY_BACKOFF_WS_CONNECT_MIN_SECONDS = 1
RETRY_BACKOFF_WS_CONNECT_MAX_SECONDS = 10
RETRY_BACKOFF_WS_CONNECT_MULTIPLIER = 2

RETRY_ATTEMPTS_WS_SEND = 3
RETRY_BACKOFF_WS_SEND_MIN_SECONDS = 0.5
RETRY_BACKOFF_WS_SEND_MAX_SECONDS = 5
RETRY_BACKOFF_WS_SEND_MULTIPLIER = 2

# Batch write settings (PostgreSQL)
DB_BATCH_SIZE = 100
DB_BATCH_FLUSH_INTERVAL_SECONDS = 5
