"""Shared CSV reading utilities for danmu analysis tools.

This module provides common functions for reading and filtering CSV files
generated by the danmu collector, supporting multiple message types.

Functions:
    read_chatmsg(filepath: str) -> list[dict]: Read chatmsg-only rows (filtered)
    read_csv_rows(filepath: str, msg_types: list[str] | None = None) -> list[dict]:
        Read CSV with optional msg_type filtering

CSV Format:
    8 columns: timestamp, username, content, user_level, user_id, room_id, msg_type, extra
    Indices:   0         1        2       3          4       5       6        7
"""

from __future__ import annotations

import csv
from pathlib import Path

from dytools.log import logger


def read_chatmsg(filepath: str) -> list[dict]:
    """Read CSV file and return only chatmsg rows with non-empty content.

    Filters out rows where msg_type != 'chatmsg' or content is empty/whitespace.
    Returns a list of dictionaries with keys: timestamp, username, content,
    user_level, user_id, room_id, msg_type, extra.

    Args:
        filepath: Path to CSV file

    Returns:
        List of dictionaries, one per valid chatmsg row. Empty list if file
        doesn't exist, is empty, or has no valid chatmsg rows.
    """
    return read_csv_rows(filepath, msg_types=["chatmsg"])


def read_csv_rows(filepath: str, msg_types: list[str] | None = None) -> list[dict]:
    """Read CSV file with optional msg_type filtering.

    Reads CSV and returns rows as list of dictionaries. Optionally filters
    by msg_type (column 6). Always filters out rows where content (column 2)
    is empty or whitespace-only.

    Args:
        filepath: Path to CSV file
        msg_types: Optional list of msg_type values to include (e.g., ["chatmsg"]).
                   If None, includes all message types (except empty content).

    Returns:
        List of dictionaries with keys: timestamp, username, content, user_level,
        user_id, room_id, msg_type, extra. Empty list if file doesn't exist, is
        empty, or has no matching rows.
    """
    path = Path(filepath)

    # Check if file exists
    if not path.exists():
        logger.info(f"File not found: {filepath}")
        return []

    # Check if file is empty
    if path.stat().st_size == 0:
        logger.info(f"File is empty: {filepath}")
        return []

    rows = []
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            reader = csv.reader(f)
            header = next(reader, None)

            if header is None:
                logger.info(f"No header in CSV file: {filepath}")
                return []

            # Expected columns: timestamp, username, content, user_level, user_id, room_id, msg_type, extra
            if len(header) < 7:
                logger.warning(f"CSV has fewer than 7 columns: {filepath} (has {len(header)})")

            for row in reader:
                # Skip rows with insufficient columns
                if len(row) < 7:
                    continue

                # Extract fields (column indices match CSV format)
                timestamp = row[0]
                username = row[1]
                content = row[2]
                user_level = row[3]
                user_id = row[4]
                room_id = row[5]
                msg_type = row[6]
                extra = row[7] if len(row) > 7 else ""

                # Filter: empty/whitespace content always excluded
                if not content.strip():
                    continue

                # Filter by msg_type if specified
                if msg_types is not None and msg_type not in msg_types:
                    continue

                rows.append(
                    {
                        "timestamp": timestamp,
                        "username": username,
                        "content": content,
                        "user_level": user_level,
                        "user_id": user_id,
                        "room_id": room_id,
                        "msg_type": msg_type,
                        "extra": extra,
                    }
                )

        if not rows:
            logger.info(f"No matching rows in CSV file: {filepath}")

        return rows

    except Exception as e:
        logger.error(f"Error reading CSV file {filepath}: {e}")
        return []
